### PR TITLE
build(conda): remove version numbers from build

### PR DESCRIPTION
**Pull request by wd15**
Ensure the conda build works on Circle CI. I've removed the version numbers from environment.yml as that never works for long with conda-forge. We'll just have to keep updating the code to stay current. I don't think that is too onerous.

### CODE REVIEW

**Comment by wd15** [comment]
Don't merge this yet. There's an issue.

**Comment by wd15** [comment]
Still broken, don't merge

**Comment by wd15** [comment]
@beyucel, you can merge this now if you're happy with it. It should fix the circle ci tests.

**Comment by beyucel** [comment]
Awesome!! Thanks Daniel!

**Pull request merged**
